plancheck: Ensure `ExpectEmptyPlan` and `ExpectNonEmptyPlan` account for output changes in addition to resource changes (#232)
Reference: https://github.com/hashicorp/terraform-plugin-testing/issues/222

Previously with new unit tests:

```
--- FAIL: Test_ExpectNonEmptyPlan_OutputChanges_None (0.90s)
    expect_non_empty_plan_test.go:17: Step 2/2 error: Pre-apply plan check(s) failed:
        expected a non-empty plan, but got an empty plan
--- FAIL: Test_ExpectEmptyPlan_OutputChanges_Error (1.00s)
    expect_empty_plan_test.go:41: Step 2/2, expected an error but got none
```